name: Build and Push Docker Image on Renovate PR

on:
  pull_request:
    branches:
      - "renovate/**"  # Triggers on any Renovate PR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: yourdockerhubusername/yourimagename:latest

      - name: PR Merge Notification
        if: github.event.pull_request.merged == true
        run: echo "Docker image rebuilt and updated for critical CVE update"
